# Generated by Django 4.2.16 on 2025-07-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicion',
            name='forma',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='proximo_rival',
        ),
        migrations.AddField(
            model_name='equipo',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='estadisticasequipo',
            name='goals_per_match',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
